name: Terraform

on:
  push
env:
  AWS_ACCESS_KEY_ID: ${{secrets.ACCESS_kEY }}
  AWS_SECRET_ACCESS_KEY: ${{secrets.SECRET_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
      #- name: Set up AWS credentials
        #run: |
         #echo "AWS_ACCESS_KEY_ID=$AKIA42FD5YMYERALMYRW" >> $GITHUB_ENV
         #echo "AWS_SECRET_ACCESS_KEY=$+Mn2UieDXyl/b9u0qfJNGCCZD266O1F0CsbA1z6r" >> $GITHUB_ENV
      - name: Init
        run: terraform init
      - name: fmt
        run: terraform validate
      - name: plan
        run: terraform plan
      - name: apply
        run: terraform apply -auto-approve
